-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 12:58:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema donkey_hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema donkey_hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `donkey_hotel` DEFAULT CHARACTER SET utf8 ;
USE `donkey_hotel` ;

-- -----------------------------------------------------
-- Table `donkey_hotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_hotel`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_hotel`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_hotel`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` INT NOT NULL,
  `roomType` VARCHAR(255) NOT NULL,
  `pricePerNight` DECIMAL(10,2) NOT NULL,
  `isAvailable` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_hotel`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_hotel`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `numberOfAdults` INT NOT NULL,
  `numberOfChildren` INT NOT NULL,
  `room_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_room_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_reservation_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `donkey_hotel`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `donkey_hotel`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_hotel`.`reservationOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_hotel`.`reservationOption` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `optionName` VARCHAR(255) NOT NULL,
  `optionPrice` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_hotel`.`reservationOption_has_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_hotel`.`reservationOption_has_reservation` (
  `reservationOption_id` INT NOT NULL,
  `reservation_id` INT NOT NULL,
  PRIMARY KEY (`reservationOption_id`, `reservation_id`),
  INDEX `fk_reservationOption_has_reservation_reservation1_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_reservationOption_has_reservation_reservationOption1_idx` (`reservationOption_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservationOption_has_reservation_reservationOption1`
    FOREIGN KEY (`reservationOption_id`)
    REFERENCES `donkey_hotel`.`reservationOption` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservationOption_has_reservation_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `donkey_hotel`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
